name: benchmarks
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: |
          pip3 install --upgrade pip
          pip3 install --upgrade setuptools wheel
          pip3 install -e .[benchmarks] --use-feature=2020-resolver
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          python -c "import nlp; print('nlp version:\t', nlp.__version__)"
